import {
    LayoutDashboard,
    Truck,
    Users,
    Package,
    HardHat,
    UserCog,
    Landmark,
    Settings,
    // Fournisseur
    Contact,
    ClipboardList,
    Banknote,
    FileInput,
    CreditCard,
    Scale,
    ScrollText,
    // Client
    ContactRound,
    FileCheck,
    FileSignature,
    CircleDollarSign,
    Receipt,
    Wallet,
    // Stock
    Boxes,
    ArrowLeftRight,
    Archive,
    // Ateliers Production
    MapPin,
    ClipboardCheck,
    TrendingDown,
    // Personnel
    BadgeCheck,
    CalendarCheck,
    // Monétaire
    MinusCircle,
    Coins,
    Vault,
    Layers,
} from 'lucide-react';

export const navigation = [
    {
        id: 'dashboard',
        label: 'Tableau de Bord',
        icon: LayoutDashboard,
        perm: 'dashboard.view',
        to: '/',
    },
    {
        id: 'fournisseurs',
        label: 'Fournisseur',
        icon: Truck,
        perm: 'fournisseurs.view',
        children: [
            { to: '/fournisseurs/fiches', label: 'Fiche Fournisseur', icon: Contact },
            { to: '/fournisseurs/bons-achats', label: 'Bon Achats', icon: ClipboardList },
            { to: '/fournisseurs/reglements-achats', label: 'Règlement Achats', icon: Banknote },
            { to: '/fournisseurs/factures-achats', label: 'Facture Achats', icon: FileInput },
            { to: '/fournisseurs/reglements-factures', label: 'Règlement Facture', icon: CreditCard },
            { to: '/fournisseurs/balance', label: 'Balance', icon: Scale },
            { to: '/fournisseurs/releve-compte', label: 'Relevé Compte', icon: ScrollText },
        ],
    },
    {
        id: 'clients',
        label: 'Client',
        icon: Users,
        perm: 'clients.view',
        children: [
            { to: '/clients/fiches', label: 'Fiche Client', icon: ContactRound },
            { to: '/clients/devis', label: 'Devis', icon: FileSignature },
            { to: '/clients/bons-vente', label: 'Bon Vente', icon: FileCheck },
            { to: '/clients/reglements-vente', label: 'Règlement Vente', icon: CircleDollarSign },
            { to: '/clients/factures-ventes', label: 'Facture Ventes', icon: Receipt },
            { to: '/clients/reglements-factures', label: 'Règlement Facture', icon: Wallet },
            { to: '/clients/balance', label: 'Balance', icon: Scale },
            { to: '/clients/releve-compte', label: 'Relevé Compte', icon: ScrollText },
        ],
    },
    {
        id: 'stock',
        label: 'Stock',
        icon: Package,
        perm: 'stock.view',
        children: [
            { to: '/stock/produits', label: 'Fiche Produit', icon: Boxes },
            { to: '/stock/mouvements', label: 'Mouvement Stock', icon: ArrowLeftRight },
            { to: '/stock/fiscal', label: 'Stock Fiscale', icon: Archive },
        ],
    },
    {
        id: 'chantiers',
        label: 'Ateliers Production',
        icon: HardHat,
        perm: 'chantiers.view',
        children: [
            { to: '/chantiers/carte', label: 'Mouvement Produit Fini', icon: MapPin },
            { to: '/chantiers/bons-commande', label: 'Bon de Commande', icon: ClipboardCheck },
            { to: '/chantiers/suivi-depenses', label: 'Suivi Dépenses', icon: TrendingDown },
        ],
    },
    {
        id: 'personnel',
        label: 'Personnel',
        icon: BadgeCheck,
        perm: 'personnel.view',
        children: [
            { to: '/personnel/fiches', label: 'Fiche Personnel', icon: Contact },
            { to: '/personnel/etat-paiement', label: 'État Paiement', icon: CalendarCheck },
        ],
    },
    {
        id: 'monetaire',
        label: 'Suivi Monétaire',
        icon: Landmark,
        perm: 'reglements.view',
        children: [
            { to: '/monetaire/transactions', label: 'Transaction', icon: ArrowLeftRight },
            { to: '/monetaire/charges', label: 'Charge', icon: MinusCircle },
            { to: '/monetaire/salaires', label: 'Salaire', icon: Coins },
            { to: '/monetaire/tresorerie', label: 'Trésorerie', icon: Vault },
        ],
    },
    {
        id: 'configuration',
        label: 'Configuration',
        icon: Settings,
        perm: 'utilisateurs.view',
        children: [
            { to: '/configuration/utilisateurs', label: 'Utilisateur', icon: UserCog },
            { to: '/configuration/familles-produits', label: 'Famille Produit', icon: Layers },
        ],
    },
];
